/* this file is generated by keymap.sh */
struct nullkey_t {
	char zgw;
};
struct charkey_t {
	char ascii;
	char shift;
	char ctrl;
};
struct stringkey_t {
	char * ascii;
};
struct numpadkey_t {
	char lock;
	char * unlock;
};

typedef void (*keyhook_t)(void * object, int code);
keyhook_t keyhook[] = {
/*0000*/(keyhook_t) &condev_t::nullkey,
/*0x01*/(keyhook_t) &condev_t::charkey,
/*0x02*/(keyhook_t) &condev_t::charkey,
/*0x03*/(keyhook_t) &condev_t::charkey,
/*0x04*/(keyhook_t) &condev_t::charkey,
/*0x05*/(keyhook_t) &condev_t::charkey,
/*0x06*/(keyhook_t) &condev_t::charkey,
/*0x07*/(keyhook_t) &condev_t::charkey,
/*0x08*/(keyhook_t) &condev_t::charkey,
/*0x09*/(keyhook_t) &condev_t::charkey,
/*0x0a*/(keyhook_t) &condev_t::charkey,
/*0x0b*/(keyhook_t) &condev_t::charkey,
/*0x0c*/(keyhook_t) &condev_t::charkey,
/*0x0d*/(keyhook_t) &condev_t::charkey,
/*0x0e*/(keyhook_t) &condev_t::charkey,
/*0x0f*/(keyhook_t) &condev_t::charkey,
/*0x10*/(keyhook_t) &condev_t::charkey,
/*0x11*/(keyhook_t) &condev_t::charkey,
/*0x12*/(keyhook_t) &condev_t::charkey,
/*0x13*/(keyhook_t) &condev_t::charkey,
/*0x14*/(keyhook_t) &condev_t::charkey,
/*0x15*/(keyhook_t) &condev_t::charkey,
/*0x16*/(keyhook_t) &condev_t::charkey,
/*0x17*/(keyhook_t) &condev_t::charkey,
/*0x18*/(keyhook_t) &condev_t::charkey,
/*0x19*/(keyhook_t) &condev_t::charkey,
/*0x1a*/(keyhook_t) &condev_t::charkey,
/*0x1b*/(keyhook_t) &condev_t::charkey,
/*0x1c*/(keyhook_t) &condev_t::charkey,
/*0x1d*/(keyhook_t) &condev_t::ctrlkey,
/*0x1e*/(keyhook_t) &condev_t::charkey,
/*0x1f*/(keyhook_t) &condev_t::charkey,
/*0x20*/(keyhook_t) &condev_t::charkey,
/*0x21*/(keyhook_t) &condev_t::charkey,
/*0x22*/(keyhook_t) &condev_t::charkey,
/*0x23*/(keyhook_t) &condev_t::charkey,
/*0x24*/(keyhook_t) &condev_t::charkey,
/*0x25*/(keyhook_t) &condev_t::charkey,
/*0x26*/(keyhook_t) &condev_t::charkey,
/*0x27*/(keyhook_t) &condev_t::charkey,
/*0x28*/(keyhook_t) &condev_t::charkey,
/*0x29*/(keyhook_t) &condev_t::charkey,
/*0x2a*/(keyhook_t) &condev_t::shiftkey,
/*0x2b*/(keyhook_t) &condev_t::charkey,
/*0x2c*/(keyhook_t) &condev_t::charkey,
/*0x2d*/(keyhook_t) &condev_t::charkey,
/*0x2e*/(keyhook_t) &condev_t::charkey,
/*0x2f*/(keyhook_t) &condev_t::charkey,
/*0x30*/(keyhook_t) &condev_t::charkey,
/*0x31*/(keyhook_t) &condev_t::charkey,
/*0x32*/(keyhook_t) &condev_t::charkey,
/*0x33*/(keyhook_t) &condev_t::charkey,
/*0x34*/(keyhook_t) &condev_t::charkey,
/*0x35*/(keyhook_t) &condev_t::charkey,
/*0x36*/(keyhook_t) &condev_t::shiftkey,
/*0x37*/(keyhook_t) &condev_t::charkey,
/*0x38*/(keyhook_t) &condev_t::altkey,
/*0x39*/(keyhook_t) &condev_t::charkey,
/*0x3a*/(keyhook_t) &condev_t::capslockkey,
/*0x3b*/(keyhook_t) &condev_t::stringkey,
/*0x3c*/(keyhook_t) &condev_t::stringkey,
/*0x3d*/(keyhook_t) &condev_t::stringkey,
/*0x3e*/(keyhook_t) &condev_t::stringkey,
/*0x3f*/(keyhook_t) &condev_t::stringkey,
/*0x40*/(keyhook_t) &condev_t::stringkey,
/*0x41*/(keyhook_t) &condev_t::stringkey,
/*0x42*/(keyhook_t) &condev_t::stringkey,
/*0x43*/(keyhook_t) &condev_t::stringkey,
/*0x44*/(keyhook_t) &condev_t::stringkey,
/*0x45*/(keyhook_t) &condev_t::numlockkey,
/*0x46*/(keyhook_t) &condev_t::scrollockkey,
/*0x47*/(keyhook_t) &condev_t::numpadkey,
/*0x48*/(keyhook_t) &condev_t::numpadkey,
/*0x49*/(keyhook_t) &condev_t::numpadkey,
/*0x4a*/(keyhook_t) &condev_t::charkey,
/*0x4b*/(keyhook_t) &condev_t::numpadkey,
/*0x4c*/(keyhook_t) &condev_t::numpadkey,
/*0x4d*/(keyhook_t) &condev_t::numpadkey,
/*0x4e*/(keyhook_t) &condev_t::charkey,
/*0x4f*/(keyhook_t) &condev_t::numpadkey,
/*0x50*/(keyhook_t) &condev_t::numpadkey,
/*0x51*/(keyhook_t) &condev_t::numpadkey,
/*0x52*/(keyhook_t) &condev_t::numpadkey,
/*0x53*/(keyhook_t) &condev_t::numpadkey,
/*0x54*/(keyhook_t) &condev_t::nullkey,
/*0x55*/(keyhook_t) &condev_t::nullkey,
/*0x56*/(keyhook_t) &condev_t::nullkey,
/*0x57*/(keyhook_t) &condev_t::stringkey,
/*0x58*/(keyhook_t) &condev_t::stringkey,
/*0x59*/(keyhook_t) &condev_t::nullkey,
/*0x5a*/(keyhook_t) &condev_t::nullkey,
/*0x5b*/(keyhook_t) &condev_t::nullkey,
/*0x5c*/(keyhook_t) &condev_t::nullkey,
/*0x5d*/(keyhook_t) &condev_t::nullkey,
/*0x5e*/(keyhook_t) &condev_t::nullkey,
/*0x5f*/(keyhook_t) &condev_t::nullkey,
/*0x60*/(keyhook_t) &condev_t::nullkey,
/*0x61*/(keyhook_t) &condev_t::nullkey,
/*0x62*/(keyhook_t) &condev_t::nullkey,
/*0x63*/(keyhook_t) &condev_t::nullkey,
/*0x64*/(keyhook_t) &condev_t::nullkey,
/*0x65*/(keyhook_t) &condev_t::nullkey,
/*0x66*/(keyhook_t) &condev_t::nullkey,
/*0x67*/(keyhook_t) &condev_t::nullkey,
/*0x68*/(keyhook_t) &condev_t::nullkey,
/*0x69*/(keyhook_t) &condev_t::nullkey,
/*0x6a*/(keyhook_t) &condev_t::nullkey,
/*0x6b*/(keyhook_t) &condev_t::nullkey,
/*0x6c*/(keyhook_t) &condev_t::nullkey,
/*0x6d*/(keyhook_t) &condev_t::nullkey,
/*0x6e*/(keyhook_t) &condev_t::nullkey,
/*0x6f*/(keyhook_t) &condev_t::nullkey,
/*0x70*/(keyhook_t) &condev_t::nullkey,
/*0x71*/(keyhook_t) &condev_t::nullkey,
/*0x72*/(keyhook_t) &condev_t::nullkey,
/*0x73*/(keyhook_t) &condev_t::nullkey,
/*0x74*/(keyhook_t) &condev_t::nullkey,
/*0x75*/(keyhook_t) &condev_t::nullkey,
/*0x76*/(keyhook_t) &condev_t::nullkey,
/*0x77*/(keyhook_t) &condev_t::nullkey,
/*0x78*/(keyhook_t) &condev_t::nullkey,
/*0x79*/(keyhook_t) &condev_t::nullkey,
/*0x7a*/(keyhook_t) &condev_t::nullkey,
/*0x7b*/(keyhook_t) &condev_t::nullkey,
/*0x7c*/(keyhook_t) &condev_t::nullkey,
/*0x7d*/(keyhook_t) &condev_t::nullkey,
/*0x7e*/(keyhook_t) &condev_t::nullkey,
/*0x7f*/(keyhook_t) &condev_t::nullkey,
};

static nullkey_t key0x00={0};
static charkey_t key0x01={27,27,0};
static charkey_t key0x02={'1','!',0};
static charkey_t key0x03={'2','@',0};
static charkey_t key0x04={'3','#',0};
static charkey_t key0x05={'4','$',0};
static charkey_t key0x06={'5','%',0};
static charkey_t key0x07={'6','^',0};
static charkey_t key0x08={'7','&',0};
static charkey_t key0x09={'8','*',0};
static charkey_t key0x0a={'9','(',0};
static charkey_t key0x0b={'0',')',0};
static charkey_t key0x0c={'-','_',0};
static charkey_t key0x0d={'=','+',0};
static charkey_t key0x0e={127,127,0};
static charkey_t key0x0f={9,9,0};
static charkey_t key0x10={'q','Q',17};
static charkey_t key0x11={'w','W',23};
static charkey_t key0x12={'e','E',5};
static charkey_t key0x13={'r','R',18};
static charkey_t key0x14={'t','T',20};
static charkey_t key0x15={'y','Y',25};
static charkey_t key0x16={'u','U',21};
static charkey_t key0x17={'i','I',9};
static charkey_t key0x18={'o','O',15};
static charkey_t key0x19={'p','P',16};
static charkey_t key0x1a={'[','{',27};
static charkey_t key0x1b={']','}',29};
static charkey_t key0x1c={'\r','\r',0};
static nullkey_t key0x1d={0};
static charkey_t key0x1e={'a','A',1};
static charkey_t key0x1f={'s','S',19};
static charkey_t key0x20={'d','D',4};
static charkey_t key0x21={'f','F',6};
static charkey_t key0x22={'g','G',7};
static charkey_t key0x23={'h','H',8};
static charkey_t key0x24={'j','J',10};
static charkey_t key0x25={'k','K',11};
static charkey_t key0x26={'l','L',12};
static charkey_t key0x27={';',':',0};
static charkey_t key0x28={'\'','"',0};
static charkey_t key0x29={'`','~',0};
static nullkey_t key0x2a={0};
static charkey_t key0x2b={'\\','|',28};
static charkey_t key0x2c={'z','Z',26};
static charkey_t key0x2d={'x','X',24};
static charkey_t key0x2e={'c','C',3};
static charkey_t key0x2f={'v','V',22};
static charkey_t key0x30={'b','B',2};
static charkey_t key0x31={'n','N',14};
static charkey_t key0x32={'m','M',13};
static charkey_t key0x33={',','<',0};
static charkey_t key0x34={'.','>',0};
static charkey_t key0x35={'/','?',0};
static nullkey_t key0x36={0};
static charkey_t key0x37={'*','*',0};
static nullkey_t key0x38={0};
static charkey_t key0x39={32,32,0};
static nullkey_t key0x3a={0};
static stringkey_t key0x3b={"\033[[A"};
static stringkey_t key0x3c={"\033[[B"};
static stringkey_t key0x3d={"\033[[C"};
static stringkey_t key0x3e={"\033[[D"};
static stringkey_t key0x3f={"\033[[E"};
static stringkey_t key0x40={"\033[17~"};
static stringkey_t key0x41={"\033[18~"};
static stringkey_t key0x42={"\033[19~"};
static stringkey_t key0x43={"\033[20~"};
static stringkey_t key0x44={"\033[21~"};
static nullkey_t key0x45={0};
static nullkey_t key0x46={0};
static numpadkey_t key0x47={'7',"\033[1~"};
static numpadkey_t key0x48={'8',"\033[A"};
static numpadkey_t key0x49={'9',"\033[5~"};
static charkey_t key0x4a={'-','-',0};
static numpadkey_t key0x4b={'4',"\033[D"};
static numpadkey_t key0x4c={'5',""};
static numpadkey_t key0x4d={'6',"\033[C"};
static charkey_t key0x4e={'+','+',0};
static numpadkey_t key0x4f={'1',"\033[4~"};
static numpadkey_t key0x50={'2',"\033[B"};
static numpadkey_t key0x51={'3',"\033[6~"};
static numpadkey_t key0x52={'0',"\033[2~"};
static numpadkey_t key0x53={'.',"\033[3"};
static nullkey_t key0x54={0};
static nullkey_t key0x55={0};
static nullkey_t key0x56={0};
static stringkey_t key0x57={"\033[23~"};
static stringkey_t key0x58={"\033[24~"};
static nullkey_t key0x59={0};
static nullkey_t key0x5a={0};
static nullkey_t key0x5b={0};
static nullkey_t key0x5c={0};
static nullkey_t key0x5d={0};
static nullkey_t key0x5e={0};
static nullkey_t key0x5f={0};
static nullkey_t key0x60={0};
static nullkey_t key0x61={0};
static nullkey_t key0x62={0};
static nullkey_t key0x63={0};
static nullkey_t key0x64={0};
static nullkey_t key0x65={0};
static nullkey_t key0x66={0};
static nullkey_t key0x67={0};
static nullkey_t key0x68={0};
static nullkey_t key0x69={0};
static nullkey_t key0x6a={0};
static nullkey_t key0x6b={0};
static nullkey_t key0x6c={0};
static nullkey_t key0x6d={0};
static nullkey_t key0x6e={0};
static nullkey_t key0x6f={0};
static nullkey_t key0x70={0};
static nullkey_t key0x71={0};
static nullkey_t key0x72={0};
static nullkey_t key0x73={0};
static nullkey_t key0x74={0};
static nullkey_t key0x75={0};
static nullkey_t key0x76={0};
static nullkey_t key0x77={0};
static nullkey_t key0x78={0};
static nullkey_t key0x79={0};
static nullkey_t key0x7a={0};
static nullkey_t key0x7b={0};
static nullkey_t key0x7c={0};
static nullkey_t key0x7d={0};
static nullkey_t key0x7e={0};
static nullkey_t key0x7f={0};

static vaddr_t keymap[] = {
(vaddr_t) &key0x00,
(vaddr_t) &key0x01,
(vaddr_t) &key0x02,
(vaddr_t) &key0x03,
(vaddr_t) &key0x04,
(vaddr_t) &key0x05,
(vaddr_t) &key0x06,
(vaddr_t) &key0x07,
(vaddr_t) &key0x08,
(vaddr_t) &key0x09,
(vaddr_t) &key0x0a,
(vaddr_t) &key0x0b,
(vaddr_t) &key0x0c,
(vaddr_t) &key0x0d,
(vaddr_t) &key0x0e,
(vaddr_t) &key0x0f,
(vaddr_t) &key0x10,
(vaddr_t) &key0x11,
(vaddr_t) &key0x12,
(vaddr_t) &key0x13,
(vaddr_t) &key0x14,
(vaddr_t) &key0x15,
(vaddr_t) &key0x16,
(vaddr_t) &key0x17,
(vaddr_t) &key0x18,
(vaddr_t) &key0x19,
(vaddr_t) &key0x1a,
(vaddr_t) &key0x1b,
(vaddr_t) &key0x1c,
(vaddr_t) &key0x1d,
(vaddr_t) &key0x1e,
(vaddr_t) &key0x1f,
(vaddr_t) &key0x20,
(vaddr_t) &key0x21,
(vaddr_t) &key0x22,
(vaddr_t) &key0x23,
(vaddr_t) &key0x24,
(vaddr_t) &key0x25,
(vaddr_t) &key0x26,
(vaddr_t) &key0x27,
(vaddr_t) &key0x28,
(vaddr_t) &key0x29,
(vaddr_t) &key0x2a,
(vaddr_t) &key0x2b,
(vaddr_t) &key0x2c,
(vaddr_t) &key0x2d,
(vaddr_t) &key0x2e,
(vaddr_t) &key0x2f,
(vaddr_t) &key0x30,
(vaddr_t) &key0x31,
(vaddr_t) &key0x32,
(vaddr_t) &key0x33,
(vaddr_t) &key0x34,
(vaddr_t) &key0x35,
(vaddr_t) &key0x36,
(vaddr_t) &key0x37,
(vaddr_t) &key0x38,
(vaddr_t) &key0x39,
(vaddr_t) &key0x3a,
(vaddr_t) &key0x3b,
(vaddr_t) &key0x3c,
(vaddr_t) &key0x3d,
(vaddr_t) &key0x3e,
(vaddr_t) &key0x3f,
(vaddr_t) &key0x40,
(vaddr_t) &key0x41,
(vaddr_t) &key0x42,
(vaddr_t) &key0x43,
(vaddr_t) &key0x44,
(vaddr_t) &key0x45,
(vaddr_t) &key0x46,
(vaddr_t) &key0x47,
(vaddr_t) &key0x48,
(vaddr_t) &key0x49,
(vaddr_t) &key0x4a,
(vaddr_t) &key0x4b,
(vaddr_t) &key0x4c,
(vaddr_t) &key0x4d,
(vaddr_t) &key0x4e,
(vaddr_t) &key0x4f,
(vaddr_t) &key0x50,
(vaddr_t) &key0x51,
(vaddr_t) &key0x52,
(vaddr_t) &key0x53,
(vaddr_t) &key0x54,
(vaddr_t) &key0x55,
(vaddr_t) &key0x56,
(vaddr_t) &key0x57,
(vaddr_t) &key0x58,
(vaddr_t) &key0x59,
(vaddr_t) &key0x5a,
(vaddr_t) &key0x5b,
(vaddr_t) &key0x5c,
(vaddr_t) &key0x5d,
(vaddr_t) &key0x5e,
(vaddr_t) &key0x5f,
(vaddr_t) &key0x60,
(vaddr_t) &key0x61,
(vaddr_t) &key0x62,
(vaddr_t) &key0x63,
(vaddr_t) &key0x64,
(vaddr_t) &key0x65,
(vaddr_t) &key0x66,
(vaddr_t) &key0x67,
(vaddr_t) &key0x68,
(vaddr_t) &key0x69,
(vaddr_t) &key0x6a,
(vaddr_t) &key0x6b,
(vaddr_t) &key0x6c,
(vaddr_t) &key0x6d,
(vaddr_t) &key0x6e,
(vaddr_t) &key0x6f,
(vaddr_t) &key0x70,
(vaddr_t) &key0x71,
(vaddr_t) &key0x72,
(vaddr_t) &key0x73,
(vaddr_t) &key0x74,
(vaddr_t) &key0x75,
(vaddr_t) &key0x76,
(vaddr_t) &key0x77,
(vaddr_t) &key0x78,
(vaddr_t) &key0x79,
(vaddr_t) &key0x7a,
(vaddr_t) &key0x7b,
(vaddr_t) &key0x7c,
(vaddr_t) &key0x7d,
(vaddr_t) &key0x7e,
(vaddr_t) &key0x7f,
};
